param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [string]$Destination = (Join-Path (Resolve-Path (Join-Path $PSScriptRoot '..')).Path 'ml\colab_bundle')
)

$sourceFiles = @(
    @{ Source = 'ml\README.md'; Target = 'README.md' },
    @{ Source = 'ml\requirements.txt'; Target = 'requirements.txt' },
    @{ Source = 'ml\sql\export_growth_dataset.sql'; Target = 'sql\export_growth_dataset.sql' },
    @{ Source = 'ml\src\feature_builder.py'; Target = 'src\feature_builder.py' },
    @{ Source = 'ml\src\who_growth.py'; Target = 'src\who_growth.py' },
    @{ Source = 'ml\src\fetch_nhanes_cycles.py'; Target = 'src\fetch_nhanes_cycles.py' },
    @{ Source = 'ml\src\fix_nhanes_columns.py'; Target = 'src\fix_nhanes_columns.py' },
    @{ Source = 'ml\src\preprocess_nhanes_raw.py'; Target = 'src\preprocess_nhanes_raw.py' },
    @{ Source = 'ml\src\train_growth_model.py'; Target = 'src\train_growth_model.py' },
    @{ Source = 'ml\src\train_lgbm_cv.py'; Target = 'src\train_lgbm_cv.py' },
    @{ Source = 'ml\src\train_lgbm_optuna.py'; Target = 'src\train_lgbm_optuna.py' },
    @{ Source = 'ml\src\train_lgbm_final.py'; Target = 'src\train_lgbm_final.py' },
    @{ Source = 'ml\src\evaluate_holdout.py'; Target = 'src\evaluate_holdout.py' },
    @{ Source = 'ml\src\predict_growth.py'; Target = 'src\predict_growth.py' }
)

New-Item -ItemType Directory -Force -Path $Destination | Out-Null

foreach ($item in $sourceFiles) {
    $sourcePath = Join-Path $Root $item.Source
    $targetPath = Join-Path $Destination $item.Target

    if (-not (Test-Path $sourcePath)) {
        Write-Warning "Missing source file: $sourcePath"
        continue
    }

    $targetDir = Split-Path $targetPath -Parent
    New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
    Copy-Item -Path $sourcePath -Destination $targetPath -Force
}

$readme = @'
# Colab ML Bundle

This folder is generated by `scripts/collect_colab_ml_files.ps1`.

What to upload to Colab:
- `requirements.txt`
- `src/feature_builder.py`
- `src/who_growth.py`
- `src/preprocess_nhanes_raw.py`
- `src/train_lgbm_optuna.py`
- `src/train_lgbm_final.py`
- Optional helper scripts in `src/`
- `sql/export_growth_dataset.sql` if you want to export from PostgreSQL first

Suggested Colab flow:
1. Upload this folder to Google Drive or Colab workspace.
2. Install dependencies from `requirements.txt`.
3. Run `preprocess_nhanes_raw.py` on raw NHANES XPT files, or use your exported CSV.
4. Run `train_lgbm_optuna.py` to tune parameters.
5. Run `train_lgbm_final.py` to train the final model bundle.

Important paths used by the scripts:
- Raw NHANES input: `ml/data/external/nhanes/raw`
- Processed output: `ml/data/external/nhanes/processed`
- Final model output: `ml/models/growth_model_lgbm_optuna.joblib`

If you only need a quick demo for presentation, you can skip the raw NHANES step and train from the already processed CSV.
'@

$readmePath = Join-Path $Destination 'README.md'
Set-Content -Path $readmePath -Value $readme -Encoding UTF8

Write-Host "Created Colab bundle at $Destination"